// src/app/edit/scripts/buildFoodsByPref.mjs
import fs from "fs";
import path from "path";
import XLSX from "xlsx";

// ====== 入力Excelのパス（必要なら変更） ======
const excelPath = path.resolve("src/app/dataset/データセットふりがな県名緯度経度.xlsx");
const outPath = path.resolve("src/app/edit/foodsByPref.generated.ts");

// ====== 県名→prefCode ======
const PREF_JA_TO_CODE = {
  "北海道": "hokkaido",
  "青森県": "aomori",
  "岩手県": "iwate",
  "宮城県": "miyagi",
  "秋田県": "akita",
  "山形県": "yamagata",
  "福島県": "fukushima",
  "茨城県": "ibaraki",
  "栃木県": "tochigi",
  "群馬県": "gunma",
  "埼玉県": "saitama",
  "千葉県": "chiba",
  "東京都": "tokyo",
  "神奈川県": "kanagawa",
  "新潟県": "niigata",
  "富山県": "toyama",
  "石川県": "ishikawa",
  "福井県": "fukui",
  "山梨県": "yamanashi",
  "長野県": "nagano",
  "岐阜県": "gifu",
  "静岡県": "shizuoka",
  "愛知県": "aichi",
  "三重県": "mie",
  "滋賀県": "shiga",
  "京都府": "kyoto",
  "大阪府": "osaka",
  "兵庫県": "hyogo",
  "奈良県": "nara",
  "和歌山県": "wakayama",
  "鳥取県": "tottori",
  "島根県": "shimane",
  "岡山県": "okayama",
  "広島県": "hiroshima",
  "山口県": "yamaguchi",
  "徳島県": "tokushima",
  "香川県": "kagawa",
  "愛媛県": "ehime",
  "高知県": "kochi",
  "福岡県": "fukuoka",
  "佐賀県": "saga",
  "長崎県": "nagasaki",
  "熊本県": "kumamoto",
  "大分県": "oita",
  "宮崎県": "miyazaki",
  "鹿児島県": "kagoshima",
  "沖縄県": "okinawa",
};

function norm(s) {
  return String(s ?? "").normalize("NFKC").trim().replace(/\s+/g, " ");
}

if (!fs.existsSync(excelPath)) {
  console.error("Excelが見つかりません:", excelPath);
  process.exit(1);
}

const wb = XLSX.readFile(excelPath);
const ws = wb.Sheets[wb.SheetNames[0]];

// ★ヘッダー無し想定：2次元配列で読む
const table = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });
if (!table.length) {
  console.error("Excelにデータがありません");
  process.exit(1);
}

// ====== 列番号設定（あなたのスクショの並びに合わせて初期値を置く） ======
// 例（スクショから推定）:
// [0]=名産, [1]=ふりがな, [2]=市, [3]=都道府県, [4]=lat, [5]=lng
const COL_FOOD = 4;
const COL_CITY = 2;
const COL_PREF = 3;

// 先頭数行を表示（確認用）
console.log("先頭3行プレビュー:");
console.log(table.slice(0, 3));

// データ行として処理
const map = {}; // prefCode -> FoodItem[]
let skipped = 0;

for (const row of table) {
  const foodName = norm(row[COL_FOOD]);
  const city = norm(row[COL_CITY]);
  const prefJa = norm(row[COL_PREF]);

  if (!foodName || !prefJa) continue;

  const prefCode = PREF_JA_TO_CODE[prefJa];
  if (!prefCode) {
    skipped++;
    continue;
  }

  (map[prefCode] ??= []).push(city ? { name: foodName, city } : { name: foodName });
}

const out =
`// AUTO-GENERATED by src/app/edit/scripts/buildFoodsByPref.mjs
// DO NOT EDIT MANUALLY.

import type { FoodItem } from "./types";

export const foodsByPref: Record<string, FoodItem[]> = ${JSON.stringify(map, null, 2)} as const;
`;

fs.writeFileSync(outPath, out, "utf-8");
console.log("Wrote:", outPath);
console.log("Pref count:", Object.keys(map).length);
console.log("Skipped rows (unknown pref):", skipped);