import fs from "fs";
import path from "path";

const iconsDir = path.resolve("public/icons/food");
const outPath = path.resolve("src/app/edit/iconManifest.generated.ts");

const files = fs
  .readdirSync(iconsDir)
  .filter((f) => /\.(png|svg|webp|jpg|jpeg)$/i.test(f));

const manifest = {};
for (const f of files) {
  const key = path.parse(f).name;
  manifest[key] = { src: `/icons/food/${f}` };
}

const content = `// AUTO-GENERATED by src/app/edit/scripts/buildIconManifest.mjs
// DO NOT EDIT MANUALLY.

export const iconManifest: Record<string, { src: string }> =
${JSON.stringify(manifest, null, 2)} as const;
`;

fs.writeFileSync(outPath, content, "utf-8");
console.log("Wrote:", outPath);
console.log("Icon count:", Object.keys(manifest).length);
console.log("Sample:", Object.entries(manifest).slice(0, 3));