// AUTO-GENERATED by src/app/edit/scripts/buildIconManifest.mjs
// DO NOT EDIT MANUALLY.

export const iconManifest: Record<string, { src: string }> =
{
  "kaki": {
    "src": "/icons/food/kaki.png"
  },
  "あげいも": {
    "src": "/icons/food/あげいも.png"
  },
  "あさり料理": {
    "src": "/icons/food/あさり料理.png"
  },
  "あんかけスパ": {
    "src": "/icons/food/あんかけスパ.png"
  },
  "あんかけ焼きそば": {
    "src": "/icons/food/あんかけ焼きそば.png"
  },
  "あんこう鍋": {
    "src": "/icons/food/あんこう鍋.png"
  },
  "いかにんじん": {
    "src": "/icons/food/いかにんじん.png"
  },
  "いくら": {
    "src": "/icons/food/いくら.png"
  },
  "いちご煮": {
    "src": "/icons/food/いちご煮.png"
  },
  "うどん": {
    "src": "/icons/food/うどん.png"
  },
  "うなぎ": {
    "src": "/icons/food/うなぎ.png"
  },
  "うなまぶし": {
    "src": "/icons/food/うなまぶし.png"
  },
  "えび料理": {
    "src": "/icons/food/えび料理.png"
  },
  "おでん": {
    "src": "/icons/food/おでん.png"
  },
  "おやき": {
    "src": "/icons/food/おやき.png"
  },
  "お好み焼き": {
    "src": "/icons/food/お好み焼き.png"
  },
  "からし蓮根": {
    "src": "/icons/food/からし蓮根.png"
  },
  "きしめん": {
    "src": "/icons/food/きしめん.png"
  },
  "きびなご料理": {
    "src": "/icons/food/きびなご料理.png"
  },
  "きりたんぽ鍋": {
    "src": "/icons/food/きりたんぽ鍋.png"
  },
  "けいちゃん焼き": {
    "src": "/icons/food/けいちゃん焼き.png"
  },
  "けの汁": {
    "src": "/icons/food/けの汁.png"
  },
  "げんこつハンバーグ": {
    "src": "/icons/food/げんこつハンバーグ.png"
  },
  "さつま揚げ": {
    "src": "/icons/food/さつま揚げ.png"
  },
  "さんが焼き": {
    "src": "/icons/food/さんが焼き.png"
  },
  "しじみ汁": {
    "src": "/icons/food/しじみ汁.png"
  },
  "しじみ貝焼き": {
    "src": "/icons/food/しじみ貝焼き.png"
  },
  "しゃも料理": {
    "src": "/icons/food/しゃも料理.png"
  },
  "しょっつる鍋": {
    "src": "/icons/food/しょっつる鍋.png"
  },
  "しらすピザ": {
    "src": "/icons/food/しらすピザ.png"
  },
  "しらす丼": {
    "src": "/icons/food/しらす丼.png"
  },
  "じゃこ天": {
    "src": "/icons/food/じゃこ天.png"
  },
  "じゃじゃ麵": {
    "src": "/icons/food/じゃじゃ麵.png"
  },
  "ずんだ餅": {
    "src": "/icons/food/ずんだ餅.png"
  },
  "せんべい汁": {
    "src": "/icons/food/せんべい汁.png"
  },
  "そうめん": {
    "src": "/icons/food/そうめん.png"
  },
  "そば": {
    "src": "/icons/food/そば.png"
  },
  "たこ焼き": {
    "src": "/icons/food/たこ焼き.png"
  },
  "だんご汁": {
    "src": "/icons/food/だんご汁.png"
  },
  "ちゃんちゃん焼き": {
    "src": "/icons/food/ちゃんちゃん焼き.png"
  },
  "ちゃんぽん": {
    "src": "/icons/food/ちゃんぽん.png"
  },
  "つけ麵": {
    "src": "/icons/food/つけ麵.png"
  },
  "とり天": {
    "src": "/icons/food/とり天.png"
  },
  "どんどん焼き": {
    "src": "/icons/food/どんどん焼き.png"
  },
  "なめろう": {
    "src": "/icons/food/なめろう.png"
  },
  "にしんそば": {
    "src": "/icons/food/にしんそば.png"
  },
  "のっぺ": {
    "src": "/icons/food/のっぺ.png"
  },
  "のどぐろ料理": {
    "src": "/icons/food/のどぐろ料理.png"
  },
  "はまぐり料理": {
    "src": "/icons/food/はまぐり料理.png"
  },
  "はらこ飯": {
    "src": "/icons/food/はらこ飯.png"
  },
  "ひっつみ汁": {
    "src": "/icons/food/ひっつみ汁.png"
  },
  "ひつまぶし": {
    "src": "/icons/food/ひつまぶし.png"
  },
  "ふぐ料理": {
    "src": "/icons/food/ふぐ料理.png"
  },
  "へきそば": {
    "src": "/icons/food/へきそば.png"
  },
  "ほうとう": {
    "src": "/icons/food/ほうとう.png"
  },
  "ぼっかけ": {
    "src": "/icons/food/ぼっかけ.png"
  },
  "ます寿司": {
    "src": "/icons/food/ます寿司.png"
  },
  "もつ鍋": {
    "src": "/icons/food/もつ鍋.png"
  },
  "もんじゃ焼き": {
    "src": "/icons/food/もんじゃ焼き.png"
  },
  "わんこそば": {
    "src": "/icons/food/わんこそば.png"
  },
  "アグー豚料理": {
    "src": "/icons/food/アグー豚料理.png"
  },
  "イカ": {
    "src": "/icons/food/イカ.png"
  },
  "イカ焼き": {
    "src": "/icons/food/イカ焼き.png"
  },
  "ウニ": {
    "src": "/icons/food/ウニ.png"
  },
  "ウニ丼": {
    "src": "/icons/food/ウニ丼.png"
  },
  "カツオ": {
    "src": "/icons/food/カツオ.png"
  },
  "カツオ料理": {
    "src": "/icons/food/カツオ料理.png"
  },
  "カツ丼": {
    "src": "/icons/food/カツ丼.png"
  },
  "カニ": {
    "src": "/icons/food/カニ.png"
  },
  "カニ料理": {
    "src": "/icons/food/カニ料理.png"
  },
  "カレー": {
    "src": "/icons/food/カレー.png"
  },
  "カレーうどん": {
    "src": "/icons/food/カレーうどん.png"
  },
  "カレーそば": {
    "src": "/icons/food/カレーそば.png"
  },
  "キムチ鍋": {
    "src": "/icons/food/キムチ鍋.png"
  },
  "クエ料理": {
    "src": "/icons/food/クエ料理.png"
  },
  "ゴーヤチャンプルー": {
    "src": "/icons/food/ゴーヤチャンプルー.png"
  },
  "サバ料理": {
    "src": "/icons/food/サバ料理.png"
  },
  "サンマ": {
    "src": "/icons/food/サンマ.png"
  },
  "サーモン料理": {
    "src": "/icons/food/サーモン料理.png"
  },
  "ザンギ": {
    "src": "/icons/food/ザンギ.png"
  },
  "ジンギスカン": {
    "src": "/icons/food/ジンギスカン.png"
  },
  "スパカツ": {
    "src": "/icons/food/スパカツ.png"
  },
  "ゼリーフライ": {
    "src": "/icons/food/ゼリーフライ.png"
  },
  "タレかつ丼": {
    "src": "/icons/food/タレかつ丼.png"
  },
  "チキン南蛮": {
    "src": "/icons/food/チキン南蛮.png"
  },
  "トルコライス": {
    "src": "/icons/food/トルコライス.png"
  },
  "バラ焼き": {
    "src": "/icons/food/バラ焼き.png"
  },
  "ヒラメ料理": {
    "src": "/icons/food/ヒラメ料理.png"
  },
  "フカヒレ料理": {
    "src": "/icons/food/フカヒレ料理.png"
  },
  "ブリ料理": {
    "src": "/icons/food/ブリ料理.png"
  },
  "ホタテ": {
    "src": "/icons/food/ホタテ.png"
  },
  "ホタルイカ料理": {
    "src": "/icons/food/ホタルイカ料理.png"
  },
  "ホルモン": {
    "src": "/icons/food/ホルモン.png"
  },
  "ホルモンうどん": {
    "src": "/icons/food/ホルモンうどん.png"
  },
  "マグロ": {
    "src": "/icons/food/マグロ.png"
  },
  "マグロ料理": {
    "src": "/icons/food/マグロ料理.png"
  },
  "ラフテー": {
    "src": "/icons/food/ラフテー.png"
  },
  "ラーメン": {
    "src": "/icons/food/ラーメン.png"
  },
  "ラーメンサラダ": {
    "src": "/icons/food/ラーメンサラダ.png"
  },
  "レモン牛乳": {
    "src": "/icons/food/レモン牛乳.png"
  },
  "上州もつ煮": {
    "src": "/icons/food/上州もつ煮.png"
  },
  "下町天丼": {
    "src": "/icons/food/下町天丼.png"
  },
  "串カツ": {
    "src": "/icons/food/串カツ.png"
  },
  "京懐石": {
    "src": "/icons/food/京懐石.png"
  },
  "伊勢海老料理": {
    "src": "/icons/food/伊勢海老料理.png"
  },
  "会津こづゆ": {
    "src": "/icons/food/会津こづゆ.png"
  },
  "佐世保バーガー": {
    "src": "/icons/food/佐世保バーガー.png"
  },
  "冷やしラーメン": {
    "src": "/icons/food/冷やしラーメン.png"
  },
  "冷や汁": {
    "src": "/icons/food/冷や汁.png"
  },
  "冷麵": {
    "src": "/icons/food/冷麵.png"
  },
  "加賀料理": {
    "src": "/icons/food/加賀料理.png"
  },
  "南蛮エビ丼": {
    "src": "/icons/food/南蛮エビ丼.png"
  },
  "台湾ラーメン": {
    "src": "/icons/food/台湾ラーメン.png"
  },
  "味噌カツ": {
    "src": "/icons/food/味噌カツ.png"
  },
  "味噌ポテト": {
    "src": "/icons/food/味噌ポテト.png"
  },
  "味噌煮込みうどん": {
    "src": "/icons/food/味噌煮込みうどん.png"
  },
  "地獄蒸し料理": {
    "src": "/icons/food/地獄蒸し料理.png"
  },
  "地鶏炭火焼": {
    "src": "/icons/food/地鶏炭火焼.png"
  },
  "大和肉鶏料理": {
    "src": "/icons/food/大和肉鶏料理.png"
  },
  "天ぷら": {
    "src": "/icons/food/天ぷら.png"
  },
  "天草大王料理": {
    "src": "/icons/food/天草大王料理.png"
  },
  "太平燕": {
    "src": "/icons/food/太平燕.png"
  },
  "奈良茶粥": {
    "src": "/icons/food/奈良茶粥.png"
  },
  "宇佐唐揚げ": {
    "src": "/icons/food/宇佐唐揚げ.png"
  },
  "宍道湖七珍料理": {
    "src": "/icons/food/宍道湖七珍料理.png"
  },
  "宮古ヤギ汁": {
    "src": "/icons/food/宮古ヤギ汁.png"
  },
  "宮崎辛麵": {
    "src": "/icons/food/宮崎辛麵.png"
  },
  "寒ブリ料理": {
    "src": "/icons/food/寒ブリ料理.png"
  },
  "寿司": {
    "src": "/icons/food/寿司.png"
  },
  "山賊焼き": {
    "src": "/icons/food/山賊焼き.png"
  },
  "常陸秋そば": {
    "src": "/icons/food/常陸秋そば.png"
  },
  "広島風お好み焼き": {
    "src": "/icons/food/広島風お好み焼き.png"
  },
  "徳島フィッシュカツ": {
    "src": "/icons/food/徳島フィッシュカツ.png"
  },
  "房総アジフライ": {
    "src": "/icons/food/房総アジフライ.png"
  },
  "手羽先": {
    "src": "/icons/food/手羽先.png"
  },
  "抹茶": {
    "src": "/icons/food/抹茶.png"
  },
  "日生カキオコ": {
    "src": "/icons/food/日生カキオコ.png"
  },
  "昆布": {
    "src": "/icons/food/昆布.png"
  },
  "昆布料理": {
    "src": "/icons/food/昆布料理.png"
  },
  "明太子料理": {
    "src": "/icons/food/明太子料理.png"
  },
  "明石焼き": {
    "src": "/icons/food/明石焼き.png"
  },
  "朴葉味噌": {
    "src": "/icons/food/朴葉味噌.png"
  },
  "柿の葉寿司": {
    "src": "/icons/food/柿の葉寿司.png"
  },
  "桜えび料理": {
    "src": "/icons/food/桜えび料理.png"
  },
  "梅とんかつ": {
    "src": "/icons/food/梅とんかつ.png"
  },
  "横浜ナポリタン": {
    "src": "/icons/food/横浜ナポリタン.png"
  },
  "比内地鶏料理": {
    "src": "/icons/food/比内地鶏料理.png"
  },
  "水炊き": {
    "src": "/icons/food/水炊き.png"
  },
  "汁なし担々麵": {
    "src": "/icons/food/汁なし担々麵.png"
  },
  "沖縄そば": {
    "src": "/icons/food/沖縄そば.png"
  },
  "沖縄天ぷら": {
    "src": "/icons/food/沖縄天ぷら.png"
  },
  "治部煮": {
    "src": "/icons/food/治部煮.png"
  },
  "津山そずり鍋": {
    "src": "/icons/food/津山そずり鍋.png"
  },
  "浜田赤天": {
    "src": "/icons/food/浜田赤天.png"
  },
  "海鮮": {
    "src": "/icons/food/海鮮.png"
  },
  "海鮮丼": {
    "src": "/icons/food/海鮮丼.png"
  },
  "海鮮炉端焼き": {
    "src": "/icons/food/海鮮炉端焼き.png"
  },
  "深川めし": {
    "src": "/icons/food/深川めし.png"
  },
  "温麺": {
    "src": "/icons/food/温麺.png"
  },
  "湯葉料理": {
    "src": "/icons/food/湯葉料理.png"
  },
  "湯豆腐": {
    "src": "/icons/food/湯豆腐.png"
  },
  "焼うどん": {
    "src": "/icons/food/焼うどん.png"
  },
  "焼きそば": {
    "src": "/icons/food/焼きそば.png"
  },
  "焼きまんじゅう": {
    "src": "/icons/food/焼きまんじゅう.png"
  },
  "焼きラーメン": {
    "src": "/icons/food/焼きラーメン.png"
  },
  "焼き鯖寿司": {
    "src": "/icons/food/焼き鯖寿司.png"
  },
  "焼き鳥": {
    "src": "/icons/food/焼き鳥.png"
  },
  "焼肉": {
    "src": "/icons/food/焼肉.png"
  },
  "焼豚玉子飯": {
    "src": "/icons/food/焼豚玉子飯.png"
  },
  "焼鯖そうめん": {
    "src": "/icons/food/焼鯖そうめん.png"
  },
  "牛タン": {
    "src": "/icons/food/牛タン.png"
  },
  "牛料理": {
    "src": "/icons/food/牛料理.png"
  },
  "牡蠣": {
    "src": "/icons/food/牡蠣.png"
  },
  "牡蠣料理": {
    "src": "/icons/food/牡蠣料理.png"
  },
  "玉こんにゃく": {
    "src": "/icons/food/玉こんにゃく.png"
  },
  "玉ねぎ料理": {
    "src": "/icons/food/玉ねぎ料理.png"
  },
  "瓦そば": {
    "src": "/icons/food/瓦そば.png"
  },
  "瓶ドン": {
    "src": "/icons/food/瓶ドン.png"
  },
  "男鹿ハタハタ料理": {
    "src": "/icons/food/男鹿ハタハタ料理.png"
  },
  "白イカ料理": {
    "src": "/icons/food/白イカ料理.png"
  },
  "白エビ丼": {
    "src": "/icons/food/白エビ丼.png"
  },
  "白熊デザート": {
    "src": "/icons/food/白熊デザート.png"
  },
  "石狩鍋": {
    "src": "/icons/food/石狩鍋.png"
  },
  "砂丘らっきょう料理": {
    "src": "/icons/food/砂丘らっきょう料理.png"
  },
  "穴子料理": {
    "src": "/icons/food/穴子料理.png"
  },
  "穴子飯": {
    "src": "/icons/food/穴子飯.png"
  },
  "笹かまぼこ": {
    "src": "/icons/food/笹かまぼこ.png"
  },
  "米沢コロッケ": {
    "src": "/icons/food/米沢コロッケ.png"
  },
  "納豆料理": {
    "src": "/icons/food/納豆料理.png"
  },
  "肉吸い": {
    "src": "/icons/food/肉吸い.png"
  },
  "芋煮": {
    "src": "/icons/food/芋煮.png"
  },
  "草加せんべい": {
    "src": "/icons/food/草加せんべい.png"
  },
  "草津温泉湯もみ料理": {
    "src": "/icons/food/草津温泉湯もみ料理.png"
  },
  "行田フライ": {
    "src": "/icons/food/行田フライ.png"
  },
  "豚みそ丼": {
    "src": "/icons/food/豚みそ丼.png"
  },
  "豚丼": {
    "src": "/icons/food/豚丼.png"
  },
  "貝焼き味噌": {
    "src": "/icons/food/貝焼き味噌.png"
  },
  "辛麺": {
    "src": "/icons/food/辛麺.png"
  },
  "近江ちゃんぽん": {
    "src": "/icons/food/近江ちゃんぽん.png"
  },
  "近江牛すき焼き": {
    "src": "/icons/food/近江牛すき焼き.png"
  },
  "那須高原ステーキ": {
    "src": "/icons/food/那須高原ステーキ.png"
  },
  "那須高原チーズ料理": {
    "src": "/icons/food/那須高原チーズ料理.png"
  },
  "酒田ワンタン面": {
    "src": "/icons/food/酒田ワンタン面.png"
  },
  "野沢菜料理": {
    "src": "/icons/food/野沢菜料理.png"
  },
  "野沢菜温泉料理": {
    "src": "/icons/food/野沢菜温泉料理.png"
  },
  "金目鯛": {
    "src": "/icons/food/金目鯛.png"
  },
  "金目鯛料理": {
    "src": "/icons/food/金目鯛料理.png"
  },
  "銚子つりきんめどん": {
    "src": "/icons/food/銚子つりきんめどん.png"
  },
  "鍋": {
    "src": "/icons/food/鍋.png"
  },
  "餃子": {
    "src": "/icons/food/餃子.png"
  },
  "馬刺し": {
    "src": "/icons/food/馬刺し.png"
  },
  "骨付鳥": {
    "src": "/icons/food/骨付鳥.png"
  },
  "高崎パスタ": {
    "src": "/icons/food/高崎パスタ.png"
  },
  "鮒ずし": {
    "src": "/icons/food/鮒ずし.png"
  },
  "鯖寿司": {
    "src": "/icons/food/鯖寿司.png"
  },
  "鯛": {
    "src": "/icons/food/鯛.png"
  },
  "鯛めし": {
    "src": "/icons/food/鯛めし.png"
  },
  "鯛料理": {
    "src": "/icons/food/鯛料理.png"
  },
  "鱧料理": {
    "src": "/icons/food/鱧料理.png"
  },
  "鳥もつ煮": {
    "src": "/icons/food/鳥もつ煮.png"
  },
  "鳥中華": {
    "src": "/icons/food/鳥中華.png"
  },
  "鴨料理": {
    "src": "/icons/food/鴨料理.png"
  },
  "鶏ちゃん料理": {
    "src": "/icons/food/鶏ちゃん料理.png"
  },
  "鶏飯": {
    "src": "/icons/food/鶏飯.png"
  },
  "黒薩摩鶏料理": {
    "src": "/icons/food/黒薩摩鶏料理.png"
  },
  "黒豚料理": {
    "src": "/icons/food/黒豚料理.png"
  }
} as const;
